# 保存一些通用的配置
DEBUG = True
# 显示的最大页数
PER_PAGE = 15

# 数据库配置
SQLALCHEMY_DATABASE_URI = "mysql://root:mysql@127.0.0.1:3306/fishers"
SQLALCHEMY_TRACK_MODIFICATIONS = False
SECRET_KEY = "JASFDKHFASJDFKLJAKJFKLAJSDKFLJAKLJKFLDJASKLJA"
